### ISSUE TITLE
Move CHANGELOG to yaml syntax

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eidolon#410]
Programmers (familiar with yaml syntax) are the only ones who read it, and it would make it easier for Fastlane and other tools to consume it. Makes sense to switch?

**Comment by ashfurrow** [comment]
Yeah, so I like this. Our CHANGELOG is pretty rigidly formatted anyway, so it makes sense. Here's an example of what the new `CHANGELOG.yml` file would look like. 

```yaml
releases:
- version: 3.3.0
  date: April 1 2015
  notes:
  - New deploy infrastructure
- version: 3.2.0
  date: March 16 2015
  notes:
  - Fix for lots with multiple images
  - Help menu bug fixed
  - Interface messaging improvements
  - New icon
- version: 3.1.1
  date: Feb 27 2015
  notes:
  - Reserve-handling
```

Format looks readable to me – at least as much as plaintext markdown is. @orta?

**Comment by orta** [comment]
Let's expand out a bit further to compare with how we use a CHANGELOG in eigen/energy:

``` yaml
beta:
- new thingy [laura]
- broke something [orta]

releases:
- version: 3.3.0
  date: April 1 2015
  notes:
  - New deploy infrastructure
- version: 3.2.0
  date: March 16 2015
  notes:
  - Fix for lots with multiple images [orta]
  - Help menu bug fixed [ash]
  - Interface messaging improvements [laura]
  - New icon [ash]
- version: 3.1.1
  date: Feb 27 2015
  notes:
  - Reserve-handling [ash]
```
